const recipes = [
      {
        id: "lemon-butter-chicken-sheet-pan",
        name: "TJ Lemon Butter Chicken Sheet Pan",
        category: "Dinner / Sheet Pan",
        source: "Frida Sofia Eats",
        sourceUrl: "https://www.fridasofiaeats.com/recipes/lemon-butter-chicken-sheet-pan",
        servings: 4,
        prepTime: "10 min",
        cookTime: "40 min",
        tags: ["Trader Joe's", "Sheet Pan", "Chicken", "Easy"],
        description: "A simple sheet pan dinner with chicken breast, baby potatoes, green beans, lemon butter, garlic, and seasoning.",
        image: "images/meals/meal-1.png",
        ingredients: [
          { name: "boneless skinless chicken thighs", quantity: "1–1.5", unit: "lb", section: "Meat" },
          { name: "baby potatoes, halved or quartered", quantity: 24, unit: "oz", section: "Produce" },
          { name: "yellow or white onion, sliced into rounds", quantity: 1, unit: "", section: "Produce" },
          { name: "bell pepper, sliced into rounds", quantity: 1, unit: "", section: "Produce" },
          { name: "olive oil", quantity: 3, unit: "tbsp", section: "Pantry" },
          { name: "butter, melted", quantity: 2, unit: "tbsp", section: "Dairy" },
          { name: "zest of 1/2 lemon", quantity: "", unit: "", section: "Produce" },
          { name: "juice of 1/2 lemon", quantity: "", unit: "", section: "Produce" },
          { name: "Dijon mustard", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "cloves of garlic, minced", quantity: 2, unit: "", section: "Produce" },
          { name: "salt", quantity: 2, unit: "tsp", section: "Pantry" },
          { name: "black pepper", quantity: 1, unit: "tsp", section: "Pantry" },
          { name: "dried oregano", quantity: 1, unit: "tsp", section: "Pantry" }
        ],
        notes: "Good option for a low-effort dinner night."
      },
      {
        id: "sweet-potato-cheeseburger-skillet",
        name: "TJ Sweet Potato Cheeseburger Skillet",
        category: "Dinner",
        source: "Frida Sofia Eats",
        sourceUrl: "https://www.fridasofiaeats.com/recipes/sweet-potato-cheeseburger-skillet",
        servings: 4,
        prepTime: "10 min",
        cookTime: "20 min",
        tags: ["Beef", "Skillet", "Sweet Potato", "Quick"],
        description: "A simple beef and sweet potato skillet with onion, garlic, ketchup, mustard, and cheddar cheese.",
        image: "images/meals/meal-2.png",
        ingredients: [
          { name: "onion, diced", quantity: 1, unit: "", section: "Produce" },
          { name: "red bell pepper, diced", quantity: 1, unit: "", section: "Produce" },
          { name: "medium sweet potatoes, diced", quantity: 3, unit: "", section: "Produce" },
          { name: "olive oil", quantity: "", unit: "", section: "Pantry" },
          { name: "salt", quantity: "", unit: "", section: "Pantry" },
          { name: "pepper", quantity: "", unit: "", section: "Pantry" },
          { name: "ground beef", quantity: 1, unit: "lb", section: "Meat" },
          { name: "cheddar cheese, grated", quantity: 3, unit: "oz", section: "Dairy" }
        ],
        notes: "Taco seasoning works well here if you want a different flavor."
      },
      {
        id: "french-onion-chicken-orzo",
        name: "TJ French Onion Chicken Orzo",
        category: "Dinner",
        source: "Frida Sofia Eats",
        sourceUrl: "https://www.fridasofiaeats.com/recipes/french-onion-chicken-orzo",
        servings: 4,
        prepTime: "10 min",
        cookTime: "35 min",
        tags: ["Chicken", "Orzo", "Comfort Food", "One Pan"],
        description: "A cozy chicken and orzo dinner with caramelized onions, beef broth, gruyere, Parmesan, and thyme.",
        image: "images/meals/meal-3.png",
        ingredients: [
          { name: "orzo", quantity: 1, unit: "cup", section: "Pantry" },
          { name: "Trader Joe’s French onion soup cubes", quantity: 2, unit: "", section: "Pantry" },
          { name: "chicken broth", quantity: 1.5, unit: "cups", section: "Pantry" },
          { name: "heavy cream", quantity: 0.75, unit: "cup", section: "Dairy" },
          { name: "baby spinach", quantity: 1, unit: "cup", section: "Produce" },
          { name: "chicken breast, cubed", quantity: 1, unit: "lb", section: "Meat" },
          { name: "salt", quantity: 1, unit: "tsp", section: "Pantry" },
          { name: "ground black pepper", quantity: 1, unit: "tsp", section: "Pantry" },
          { name: "garlic powder", quantity: 1, unit: "tsp", section: "Pantry" },
          { name: "Parmesan for sprinkling", quantity: "", unit: "", section: "Dairy" }
        ],
        notes: "Keep extra broth nearby if the orzo absorbs too much liquid."
      },
      {
        id: "spinach-artichoke-orzo",
        name: "TJ Spinach and Artichoke Orzo",
        category: "Dinner / Vegetarian",
        source: "Frida Sofia Eats",
        sourceUrl: "https://www.fridasofiaeats.com/recipes/spinach-and-artichoke-orzo",
        servings: 4,
        prepTime: "10 min",
        cookTime: "20 min",
        tags: ["Vegetarian", "Orzo", "Creamy", "Trader Joe's"],
        description: "A creamy vegetarian orzo dish with spinach, artichokes, cream cheese, Parmesan, and lemon juice.",
        image: "images/meals/meal-4.png",
        ingredients: [
          { name: "orzo pasta", quantity: 1, unit: "lbs", section: "Pantry" },
          { name: "chicken sausage (I LOVE this cheddar one from Trader Joe's)", quantity: 12, unit: "oz", section: "Meat" },
          { name: "baby spinach", quantity: 1, unit: "cup", section: "Produce" },
          { name: "cherry tomatoes", quantity: 1.5, unit: "cup", section: "Produce" },
          { name: "spinach and artichoke dip from Trader Joe's or wherever you can find one. Room temperature. You can place the dip in the fridge overnight or for a couple of hours.", quantity: 1, unit: "", section: "Dairy" },
          { name: "chicken or vegetables broth", quantity: 3, unit: "cups", section: "Pantry" }
        ],
        notes: "Can be served as a vegetarian main or as a side with chicken."
      },
      {
        id: "chicken-noodle-bowl",
        name: "TJ Chicken Noodle Bowl",
        category: "Dinner",
        source: "Frida Sofia Eats",
        sourceUrl: "https://www.fridasofiaeats.com/recipes/shrimp-noodle-bowl",
        servings: 4,
        prepTime: "10 min",
        cookTime: "15 min",
        tags: ["Chicken", "Noodles", "Quick", "Trader Joe's"],
        description: "A quick chicken noodle bowl with stir fry noodles, carrots, cucumbers, garlic, soy sauce, and sesame oil.",
        image: "images/meals/meal-5.png",
        ingredients: [
          { name: "packets of wheat noodles (you will need 2 boxes)", quantity: 4, unit: "", section: "Pantry" },
          { name: "bell peppers, sliced", quantity: 2, unit: "", section: "Produce" },
          { name: "chicken breast", quantity: 1, unit: "lb", section: "Meat" },
          { name: "soyaki sauce", quantity: 0.5, unit: "cup", section: "Pantry" },
          { name: "reserved noodle water", quantity: 1/3, unit: "cup", section: "Pantry" },
          { name: "salt", quantity: "", unit: "", section: "Pantry" },
          { name: "pepper", quantity: "", unit: "", section: "Pantry" },
          { name: "olive oil", quantity: "", unit: "", section: "Pantry" },
          { name: "Butter", quantity: 1, unit: "tbsp", section: "Dairy" }
        ],
        notes: "This is adapted from the shrimp version by replacing shrimp with chicken."
      },
      {
        id: "salsa-verde-chicken-couscous",
        name: "TJ Salsa Verde Chicken and Couscous",
        category: "Dinner",
        source: "Frida Sofia Eats",
        sourceUrl: "https://www.fridasofiaeats.com/recipes/salsa-verde-chicken-and-couscous",
        servings: 4,
        prepTime: "10 min",
        cookTime: "20 min",
        tags: ["Chicken", "Couscous", "Quick", "Trader Joe's"],
        description: "A quick chicken dinner with couscous, chicken broth, salsa verde, garlic, and olive oil.",
        image: "images/meals/meal-6.png",
        ingredients: [
          { name: "couscous", quantity: 12, unit: "oz", section: "Pantry" },
          { name: "chicken thighs, boneless and skinless", quantity: 1.5, unit: "lbs", section: "Meat" },
          { name: "salsa verde", quantity: 12, unit: "oz", section: "Pantry" }
        ],
        notes: "Good for leftovers and easy to customize."
      },
      {
        id: "soyaki-beef-bowl",
        name: "TJ Soyaki Beef Bowl (Original)",
        category: "Dinner",
        source: "Frida Sofia Eats",
        sourceUrl: "https://www.fridasofiaeats.com/recipes/soyaki-beef-bowl",
        servings: 4,
        prepTime: "10 min",
        cookTime: "15 min",
        tags: ["Beef", "Rice Bowl", "Quick", "Trader Joe's"],
        description: "A fast rice bowl with ground beef, white rice, Soyaki sauce, garlic, and green onions.",
        image: "images/meals/meal-7.png",
        ingredients: [
          { name: "ground beef", quantity: 1, unit: "lb", section: "Meat" },
          { name: "scallions (about ½ Trader Joe’s bunch), sliced and whites/greens separated", quantity: 3, unit: "oz", section: "Produce" },
          { name: "Trader Joe’s Soyaki sauce", quantity: 1/3, unit: "cup", section: "Pantry" },
          { name: "water", quantity: 1/3, unit: "cup", section: "Pantry" },
          { name: "eggs", quantity: 4, unit: "", section: "Dairy" },
          { name: "basmati rice", quantity: 1.5, unit: "cups", section: "Pantry" },
          { name: "olive oil", quantity: "", unit: "", section: "Pantry" },
          { name: "salt and pepper", quantity: "", unit: "", section: "Pantry" },
          { name: "avocado (for serving)", quantity: "", unit: "", section: "Produce" }
        ],
        notes: "One of the fastest weeknight options."
      },
      {
        id: "slow-cooker-steak-and-potatoes",
        name: "TJ Slow Cooker Steak and Potatoes",
        category: "Dinner / Slow Cooker",
        source: "Frida Sofia Eats",
        sourceUrl: "https://www.fridasofiaeats.com/recipes/slow-cooker-steak-and-potatoes",
        servings: 4,
        prepTime: "10 min",
        cookTime: "6 hrs",
        tags: ["Beef", "Slow Cooker", "Potatoes", "Comfort Food"],
        description: "A slow cooker steak and potato dinner with garlic, beef broth, olive oil, and Italian seasoning.",
        image: "images/meals/meal-8.png",
        ingredients: [
          { name: "Black Angus petite sirloin steak (leave whole or cut into 2–3 large pieces)", quantity: "1.5–2", unit: "lb", section: "Meat" },
          { name: "potatoes, cut into large 2–3 inch chunks", quantity: 1.5, unit: "lb", section: "Produce" },
          { name: "carrots, cut into large pieces", quantity: 3, unit: "", section: "Produce" },
          { name: "large onion, sliced thick", quantity: 1, unit: "", section: "Produce" },
          { name: "tomato paste", quantity: 3, unit: "tbsp", section: "Pantry" },
          { name: "cloves garlic, minced", quantity: 6, unit: "", section: "Produce" },
          { name: "beef broth", quantity: 1.5, unit: "cups", section: "Pantry" },
          { name: "Worcestershire sauce", quantity: 2, unit: "tbsp", section: "Pantry" },
          { name: "olive oil, divided", quantity: 4, unit: "tbsp", section: "Pantry" },
          { name: "black pepper", quantity: 1, unit: "tsp", section: "Pantry" },
          { name: "paprika", quantity: 1, unit: "tsp", section: "Pantry" },
          { name: "dried thyme or Italian seasoning", quantity: 1, unit: "tsp", section: "Pantry" },
          { name: "salt, to taste at the end", quantity: "", unit: "", section: "Pantry" }
        ],
        notes: "Good make-ahead dinner."
      },
      {
        id: "chicken-sausage-pasta-bake",
        name: "TJ Chicken Sausage Pasta Bake",
        category: "Dinner",
        source: "Frida Sofia Eats",
        sourceUrl: "https://www.fridasofiaeats.com/recipes/pasta-chicken-sausage-bake",
        servings: 4,
        prepTime: "10 min",
        cookTime: "25 min",
        tags: ["Chicken Sausage", "Pasta", "Bake", "Easy"],
        description: "A pasta bake with chicken sausage, pasta, crushed tomatoes, garlic, mozzarella, Parmesan, and Italian seasoning.",
        image: "images/meals/meal-9.png",
        ingredients: [
          { name: "pasta, I used farfalle", quantity: 1, unit: "lbs", section: "Pantry" },
          { name: "cherry tomatoes", quantity: 1, unit: "pint", section: "Produce" },
          { name: "chicken sausage, I used sweet Italian", quantity: "12 oz/340 g", unit: "", section: "Meat" },
          { name: "Boursin garlic and herb cheese spread", quantity: "5 oz/150g", unit: "", section: "Dairy" },
          { name: "chicken bone broth or chicken broth", quantity: 4, unit: "cups", section: "Pantry" },
          { name: "minced garlic", quantity: 1, unit: "tbsp", section: "Produce" },
          { name: "sour cream", quantity: 0.5, unit: "cup", section: "Dairy" },
          { name: "Parmesan cheese", quantity: 0.25, unit: "cup", section: "Dairy" }
        ],
        notes: "Good easy pasta-bake option."
      },
      {
        id: "cheesy-chicken-sausage-rice-orzo",
        name: "TJ Cheesy Chicken Sausage Rice and Orzo",
        category: "Dinner",
        source: "Frida Sofia Eats",
        sourceUrl: "https://www.fridasofiaeats.com/recipes/baked-cheesy-chicken-sausage-rice-and-orzo",
        servings: 4,
        prepTime: "10 min",
        cookTime: "30 min",
        tags: ["Chicken Sausage", "Rice", "Orzo", "Bake"],
        description: "A cheesy baked rice and orzo dinner with chicken sausage, chicken broth, garlic, butter, and cheddar cheese.",
        image: "images/meals/meal-10.png",
        ingredients: [
          { name: "packages Trader Joe’s Frozen Orzo Pilaf Mix or about 3 cups dry orzo", quantity: 2, unit: "", section: "Pantry" },
          { name: "chicken sausage (I used Trader Joe’s Unexpected Cheddar), sliced", quantity: 12, unit: "oz", section: "Meat" },
          { name: "riced cauliflower", quantity: 1, unit: "cup", section: "Produce" },
          { name: "green peas", quantity: 1, unit: "cup", section: "Produce" },
          { name: "container Trader Joe’s Spinach & Artichoke Dip (8.82 oz)", quantity: 1, unit: "", section: "Dairy" },
          { name: "chicken broth", quantity: 2, unit: "cups", section: "Pantry" },
          { name: "black pepper or red pepper flakes to taste", quantity: "", unit: "", section: "Pantry" }
        ],
        notes: "If picky eaters object to extras, keep this one simple."
      },
      {
        id: "spicy-quick-chicken-chili",
        name: "TJ Spicy Quick Chicken Chili",
        category: "Dinner",
        source: "Trader Joe's",
        sourceUrl: "https://www.traderjoes.com/home/recipes/spicy-quick-chicken-chili",
        servings: 4,
        prepTime: "10 min",
        cookTime: "25 min",
        tags: ["Chicken", "Chili", "Quick", "Spicy"],
        description: "A fast, hearty chicken chili with beans, corn, and a creamy finish from cream cheese.",
        image: "images/meals/meal-11.png",
        ingredients: [
          { name: "TJ's All Natural Ground Chicken", quantity: 1, unit: "lb", section: "Meat" },
          { name: "TJ's Jumbo White Onion", quantity: 1, unit: "", section: "Produce" },
          { name: "TJ's Taco Seasoning Mix", quantity: "", unit: "", section: "Pantry" },
          { name: "TJ's Organic Kidney Beans", quantity: 15.5, unit: "oz can", section: "Pantry" },
          { name: "TJ's Diced & Fire Roasted Organic Tomatoes with Green Chiles", quantity: 14.5, unit: "oz can", section: "Pantry" },
          { name: "TJ's Organic Tomato Paste", quantity: 2, unit: "Tbsp", section: "Pantry" },
          { name: "TJ's Olive Oil of your choice", quantity: "", unit: "", section: "Pantry" },
          { name: "TJ's Salt & Pepper", quantity: "", unit: "", section: "Pantry" }
        ],
        notes: "Great for leftovers. Adjust spice level by increasing or reducing red pepper flakes."
      },
      {
        id: "soyaki-shaved-steak-bowl",
        name: "TJ Soyaki Shaved Steak Bowl",
        category: "Dinner",
        source: "5 Items or Less",
        sourceUrl: "https://5itemsorless.com/one-pan-soyaki-shaved-steak-with-bell-pepperrs-over-rice/",
        servings: 4,
        prepTime: "10 min",
        cookTime: "20 min",
        tags: ["Beef", "Rice Bowl", "Quick", "Trader Joe's"],
        description: "A quick rice bowl with shaved steak, peppers, onions, garlic, and Trader Joe's Soyaki sauce.",
        image: "images/meals/meal-12.png",
        ingredients: [
          { name: "Tri-Color Bell Peppers", quantity: 1, unit: "pack", section: "Produce" },
          { name: "Sweet Onion", quantity: 0.5, unit: "", section: "Produce" },
          { name: "Soyaki Sauce", quantity: 0.5, unit: "cup", section: "Pantry" },
          { name: "Jasmine Rice (frozen)", quantity: 1, unit: "pouch", section: "Frozen" },
          { name: "Shaved Steak", quantity: 1, unit: "lb", section: "Meat" },
          { name: "olive oil", quantity: "", unit: "", section: "Pantry" },
          { name: "green onion (optional garnish)", quantity: "", unit: "", section: "Produce" }
        ],
        notes: "Slice vegetables thin so they cook quickly. Great weeknight option."
      },
      {
        id: "beef-stir-fry-noodles",
        name: "TJ Soyaki Shaved Steak Bowl",
        category: "Dinner",
        source: "5 Items or Less",
        sourceUrl: "https://5itemsorless.com/4-ingredient-beef-stir-fry-with-noodles-easy-trader-joes-dinner/",
        servings: 4,
        prepTime: "10 min",
        cookTime: "15 min",
        tags: ["Beef", "Noodles", "Stir Fry", "Quick"],
        description: "A fast stir fry with shaved steak, pre-cooked noodles, vegetables, and Soyaki sauce.",
        image: "images/meals/meal-13.png",
        ingredients: [
          { name: "Shaved Steak", quantity: 1, unit: "lb", section: "Meat" },
          { name: "Trader Joe's Asian Style Stir Fry Vegetables w stir fry sauce (frozen)", quantity: 1, unit: "package", section: "Frozen" },
          { name: "General Tsao Sauce", quantity: 0.25, unit: "cup", section: "Pantry" },
          { name: "Thai Wheat Noodles", quantity: 1, unit: "pouch", section: "Refrigerated" },
          { name: "olive oil", quantity: "", unit: "", section: "Pantry" },
          { name: "salt & pepper", quantity: "", unit: "", section: "Pantry" }
        ],
        notes: "Very quick meal—great for busy nights."
      },
      {
        id: "sesame-chicken-veggie-rice-bowl",
        name: "TJ Sesame Chicken Veggie Rice Bowl",
        category: "Dinner",
        source: "5 Items or Less",
        sourceUrl: "https://5itemsorless.com/easy-20-minute-sesame-chicken-veggie-rice-bowls/",
        servings: 4,
        prepTime: "10 min",
        cookTime: "20 min",
        tags: ["Chicken", "Rice Bowl", "Stir Fry", "Quick"],
        description: "A simple rice bowl with chicken, vegetables, and sesame sauce.",
        image: "images/meals/meal-14.png",
        ingredients: [
          { name: "Grilled Chicken Breasts, pre-cooked", quantity: 12, unit: "oz", section: "Meat" },
          { name: "Toasted Sesame Dressing", quantity: 0.25, unit: "cup", section: "Pantry" },
          { name: "Organic Jasmine Rice", quantity: 1, unit: "pouch", section: "Frozen" },
          { name: "Asian Style Vegetable Stir Fry", quantity: 18, unit: "oz", section: "Frozen" },
          { name: "olive oil", quantity: "", unit: "", section: "Pantry" },
          { name: "salt", quantity: "", unit: "", section: "Pantry" },
          { name: "pepper", quantity: "", unit: "", section: "Pantry" },
          { name: "garlic powder", quantity: "", unit: "", section: "Pantry" },
          { name: "Everything but the bagel seasoning or sesame seeds (optional)", quantity: "", unit: "", section: "Pantry" }
        ],
        notes: "Add extra sesame oil for more flavor."
      },
      {
        id: "chicken-wonton-stir-fry",
        name: "TJ Chicken Wonton Stir Fry",
        category: "Dinner",
        source: "5 Items or Less",
        sourceUrl: "https://5itemsorless.com/chicken-wonton-stir-fry/",
        servings: 4,
        prepTime: "10 min",
        cookTime: "15 min",
        tags: ["Trader Joe's", "Wontons", "Stir Fry", "Quick"],
        description: "A quick stir fry with chicken wontons, frozen vegetables, Soyaki sauce, garlic, sesame oil, and green onions.",
        image: "images/meals/meal-15.png",
        ingredients: [
          { name: "Chicken Cilantro Mini Wontons", quantity: 12, unit: "oz", section: "Frozen" },
          { name: "Asian Style Vegetable Stir Fry", quantity: 18, unit: "oz", section: "Frozen" },
          { name: "General Tsao Stir Fry Sauce", quantity: 0.5, unit: "cup", section: "Pantry" },
          { name: "olive oil", quantity: "", unit: "", section: "Pantry" },
          { name: "Umami Seasoning", quantity: "", unit: "", section: "Pantry" },
          { name: "salt & pepper", quantity: "", unit: "", section: "Pantry" }
        ],
        notes: "Good fast freezer meal. Keep the wontons whole and avoid over-stirring once they are heated."
      },
      {
        id: "pesto-chicken-sandwich",
        name: "TJ Pesto Chicken Sandwich",
        category: "Dinner / Sandwiches",
        source: "5 Items or Less",
        sourceUrl: "https://5itemsorless.com/5-ingredient-pesto-chicken-sandwich-easy-trader-joes-meal/",
        servings: 4,
        prepTime: "10 min",
        cookTime: "15 min",
        tags: ["Chicken", "Sandwich", "Pesto", "Quick"],
        description: "A pesto chicken sandwich with Havarti cheese, brioche buns, pesto, tomatoes, and butter.",
        image: "images/meals/meal-16.png",
        ingredients: [
          { name: "Pesto Chicken", quantity: 1, unit: "pkg", section: "Meat" },
          { name: "Havarti cheese (about an oz each slice)", quantity: 4, unit: "slices", section: "Dairy" },
          { name: "Brioche buns", quantity: "", unit: "", section: "Pantry" },
          { name: "Pesto (about an ounce each sandwich)", quantity: "", unit: "", section: "Refrigerated" },
          { name: "Tomato", quantity: 1, unit: "", section: "Produce" },
          { name: "butter", quantity: "", unit: "", section: "Dairy" }
        ],
        notes: "Good quick sandwich dinner."
      },
      {
        id: "angela-josh-spicy-soy-garlic-turkey-bowl",
        name: "A&J Spicy Soy Garlic Turkey Bowl",
        category: "Dinner",
        source: "Angela and Josh's Cookbook",
        sourceUrl: "https://photos.app.goo.gl/KjA6usSBK4D7V5Bg8",
        servings: 4,
        prepTime: "15 min",
        cookTime: "25 min",
        tags: ["Turkey", "Rice Bowl", "Spicy", "Quick"],
        description: "A spicy soy garlic turkey bowl with rice, bok choy, pickled radishes, and a creamy curry sauce.",
        image: "images/meals/meal-24.png",
        ingredients: [
          { name: "jasmine rice", quantity: 1, unit: "cup", section: "Pantry" },
          { name: "water", quantity: 1.5, unit: "cups", section: "Pantry" },
          { name: "salt", quantity: 0.5, unit: "teaspoon", section: "Pantry" },
      
          { name: "apple cider vinegar", quantity: 1, unit: "tablespoon", section: "Pantry" },
          { name: "sesame oil", quantity: 1, unit: "tablespoon", section: "Pantry" },
          { name: "green onions, sliced", quantity: 2, unit: "", section: "Produce" },
          { name: "salt", quantity: 1, unit: "teaspoon", section: "Pantry" },
          { name: "freshly ground black pepper", quantity: 1, unit: "teaspoon", section: "Pantry" },
          { name: "radishes (about 3 to 4), sliced into thin rounds", quantity: 3, unit: "ounces", section: "Produce" },
      
          { name: "mayonnaise", quantity: 0.25, unit: "cup", section: "Dairy" },
          { name: "red curry paste", quantity: 2, unit: "tablespoons", section: "Pantry" },
          { name: "honey", quantity: 1, unit: "tablespoon", section: "Pantry" },
      
          { name: "soy sauce", quantity: 0.25, unit: "cup", section: "Pantry" },
          { name: "brown sugar", quantity: 0.25, unit: "cup", section: "Pantry" },
          { name: "garlic cloves, minced", quantity: 2, unit: "", section: "Produce" },
          { name: "minced ginger", quantity: 1, unit: "teaspoon", section: "Produce" },
          { name: "red pepper flakes", quantity: 0.25, unit: "teaspoon", section: "Pantry" },
          { name: "coconut oil", quantity: 1, unit: "tablespoon", section: "Pantry" },
          { name: "ground turkey", quantity: 1.5, unit: "pounds", section: "Meat" },
          { name: "baby bok choy, chopped", quantity: 2, unit: "stalks", section: "Produce" },
          { name: "sliced green onions and sesame seeds, for topping", quantity: "", unit: "", section: "Produce" }
        ],
        notes: "Great balance of spicy, savory, and fresh."
      },
      {
        id: "21",
        name: "A&J Orecchiette with Chicken Sausage, Fennel, and Asparagus",
        category: "Dinner",
        source: "Angela and Josh's Cookbook",
        sourceUrl: "https://photos.app.goo.gl/7nG6uxZtAQ3EUuQy6",
        servings: 4,
        prepTime: "10 min",
        cookTime: "25 min",
        tags: ["Chicken Sausage", "Pasta", "Asparagus", "Dinner"],
        description: "Orecchiette pasta with chicken sausage, fennel, asparagus, lemon, capers, and pecorino romano.",
        image: "images/meals/meal-25.png",
        ingredients: [
          { name: "extra-virgin olive oil", quantity: 3, unit: "tablespoons", section: "Pantry" },
          { name: "uncooked Italian chicken sausage, casing removed", quantity: 1, unit: "pound", section: "Meat" },
          { name: "large fennel bulb, finely chopped", quantity: 1, unit: "", section: "Produce" },
          { name: "garlic cloves, minced", quantity: 3, unit: "", section: "Produce" },
          { name: "salt", quantity: 1, unit: "teaspoon", section: "Pantry" },
          { name: "freshly ground black pepper", quantity: 0.5, unit: "teaspoon", section: "Pantry" },
          { name: "crushed red pepper flakes", quantity: 0.25, unit: "teaspoon", section: "Pantry" },
          { name: "dry white wine", quantity: 1, unit: "cup", section: "Pantry" },
          { name: "chicken broth", quantity: 2, unit: "cups", section: "Pantry" },
          { name: "lemon juice", quantity: 0.5, unit: "cup", section: "Produce" },
          { name: "capers", quantity: 2, unit: "tablespoons", section: "Pantry" },
          { name: "orecchiette", quantity: 8, unit: "ounces", section: "Pantry" },
          { name: "asparagus spears, cut into 2-inch pieces", quantity: 0.5, unit: "pound", section: "Produce" },
          { name: "shaved Pecorino Romano, for topping", quantity: 0.5, unit: "cup", section: "Dairy" }
        ],
        notes: "Bright, savory pasta dinner with chicken sausage and vegetables."
      },
      {
        id: "teriyaki-green-bean-beef",
        name: "ALDI Teriyaki Green Bean Beef",
        category: "Dinner",
        source: "Frida Sofia Eats",
        sourceUrl: "https://www.fridasofiaeats.com/recipes/teriyaki-green-been-beef",
        servings: 4,
        prepTime: "10 min",
        cookTime: "20 min",
        tags: ["Beef", "Rice Bowl", "Quick", "Aldi's"],
        description: "A simple teriyaki beef and green bean bowl served over rice.",
        image: "images/meals/meal-17.png",
        ingredients: [
          { name: "raw basmati rice", quantity: 2, unit: "cups", section: "Pantry" },
          { name: "ground beef", quantity: 1, unit: "lb", section: "Meat" },
          { name: "teriyaki stir-fry sauce (store-bought or homemade, see below)", quantity: 14.5, unit: "oz", section: "Pantry" },
          { name: "green beans, cut", quantity: 12, unit: "oz", section: "Produce" },
          { name: "olive oil", quantity: "", unit: "", section: "Pantry" }
        ],
        notes: ""
      },
      {
        id: "chicken-adobo",
        name: "5 Ingredient Chicken Adobo",
        category: "Dinner",
        source: "5 Ingredient Tin Box",
        sourceUrl: "https://photos.app.goo.gl/cPGSLeh2UbkvVWi77",
        servings: 6,
        prepTime: "20 min",
        cookTime: "60 min",
        tags: ["Chicken", "Filipino", "Dinner"],
        description: "Classic chicken adobo with soy sauce, vinegar, garlic, and bay leaves.",
        image: "images/meals/meal-18.png",
        ingredients: [
          { name: "cider vinegar", quantity: 0.5, unit: "cup", section: "Pantry" },
          { name: "reduced-sodium soy sauce", quantity: 0.5, unit: "cup", section: "Pantry" },
          { name: "cloves garlic, minced", quantity: 4, unit: "", section: "Produce" },
          { name: "bay leaves", quantity: 3, unit: "", section: "Pantry" },
          { name: "black pepper", quantity: 1, unit: "teaspoon", section: "Pantry" },
          { name: "bone-in skin-on chicken thighs (about 6)", quantity: 2.5, unit: "pounds", section: "Meat" },
          { name: "sliced green onion (optional)", quantity: "", unit: "", section: "Produce" },
          { name: "hot cooked rice (optional)", quantity: "", unit: "", section: "Pantry" }
        ],
        notes: "Grandma's favorite!"
      },
      {
        id: "taco-pasta-skillet",
        name: "5 Ingredient Taco Pasta Skillet",
        category: "Dinner / Skillet",
        source: "5 Ingredient Tin Box",
        sourceUrl: "https://photos.app.goo.gl/KvS2iXAjPTY2LhMCA",
        servings: 6,
        prepTime: "10 min",
        cookTime: "20 min",
        tags: ["Skillet", "Beef", "Pasta", "One-Pot", "Family-Friendly", "Quick"],
        description: "A quick and hearty one-pot meal combining taco-seasoned ground beef, rotini pasta, and salsa for an easy weeknight dinner.",
        image: "images/meals/meal-19.png",
        ingredients: [
          { name: "ground beef", quantity: 1, unit: "lb", section: "Meat" },
          { name: "Yellow onion, chopped", quantity: 1, unit: "", section: "Produce" },
          { name: "taco seasoning mix", quantity: 1, unit: "package", section: "Pantry" },
          { name: "water", quantity: 2, unit: "cups", section: "Pantry" },
          { name: "medium salsa", quantity: 16, unit: "oz", section: "Pantry" },
          { name: "salt", quantity: 0.25, unit: "tsp", section: "Pantry" },
          { name: "rotini pasta, uncooked", quantity: 8, unit: "oz", section: "Pantry" },
          { name: "shredded cheddar or Mexican blend cheese (optional)", quantity: "", unit: "", section: "Dairy" }
        ],
        notes: "Taco, taco, man. I want to be, a Taco man!"
      },
      {
        id: "crispy-chickpeas-with-beef",
        name: "NYT Crispy Chickpeas with Beef",
        category: "Dinner / Skillet",
        source: "New York Times",
        sourceUrl: "https://cooking.nytimes.com/recipes/8024-crispy-chickpeas-with-beef",
        servings: 4,
        prepTime: "N/A",
        cookTime: "30 min",
        tags: ["Skillet", "Beef", "Chickpeas", "High-Protein", "Pantry-Friendly", "Simple","New York Times"],
        description: "A savory skillet dish combining crispy chickpeas with seasoned ground beef, garlic, cumin, and chile powder for a bold, protein-rich meal.",
        image: "images/meals/meal-20.png",
        ingredients: [
          { name: "ground beef (or other ground meat)", quantity: "0.5–1", unit: "lb", section: "Meat" },
          { name: "chickpeas (canned), drained", quantity: 1, unit: "28 oz can", section: "Pantry" },
          { name: "ground cumin", quantity: 2, unit: "tsp", section: "Pantry" },
          { name: "chile powder", quantity: 1, unit: "tsp", section: "Pantry" },
          { name: "garlic, minced", quantity: 2, unit: "tsp", section: "Produce" },
          { name: "salt", quantity: "", unit: "", section: "Pantry" },
          { name: "black pepper", quantity: "", unit: "", section: "Pantry" },
          { name: "olive oil", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "cilantro or parsley, minced (optional)", quantity: "", unit: "", section: "Produce" }
        ],
        notes: "9/11 was an inside job."
      },
      {
        id: "sausage-and-barley-soup-with-greens",
        name: "NYT Sausage and Barley Soup with Greens",
        category: "Dinner / Soup",
        source: "New York Times",
        sourceUrl: "https://cooking.nytimes.com/recipes/1026506-sausage-and-barley-soup-with-greens",
        servings: "6–8",
        prepTime: "10 min",
        cookTime: "45 min",
        tags: ["Soup", "Sausage", "Hearty", "Vegetables", "One-Pot", "Comfort Food","New York Times"],
        description: "A hearty, comforting soup with Italian sausage, pearled barley, vegetables, and tender greens in a rich broth.",
        image: "images/meals/meal-21.png",
        ingredients: [
          { name: "olive oil", quantity: 2, unit: "tbsp", section: "Pantry" },
          { name: "Italian sausage (pork or chicken), casings removed", quantity: 8, unit: "oz", section: "Meat" },
          { name: "Yellow onion, chopped", quantity: 1, unit: "", section: "Produce" },
          { name: "carrots, peeled and chopped", quantity: 3, unit: "", section: "Produce" },
          { name: "salt", quantity: "", unit: "", section: "Pantry" },
          { name: "black pepper", quantity: "", unit: "", section: "Pantry" },
          { name: "stock or water", quantity: 6, unit: "cups", section: "Pantry" },
          { name: "diced tomatoes (canned)", quantity: 14, unit: "oz", section: "Pantry" },
          { name: "pearled barley", quantity: 0.5, unit: "cup", section: "Pantry" },
          { name: "tender greens (spinach or baby kale)", quantity: 8, unit: "oz", section: "Produce" },
          { name: "red wine vinegar or apple cider vinegar", quantity: 2, unit: "tbsp", section: "Pantry" },
          { name: "grated Parmesan (optional)", quantity: "", unit: "", section: "Dairy" },
          { name: "fresh herbs (optional)", quantity: "", unit: "", section: "Produce" }
        ],
        notes: "Epstein didn't kill himself."
      },
      {
        id: "sausage-tortellini-soup",
        name: "NYT Sausage Tortellini Soup",
        category: "Dinner / Soup",
        source: "New York Times",
        sourceUrl: "https://cooking.nytimes.com/recipes/1024144-sausage-tortellini-soup",
        servings: 4,
        prepTime: "10 min",
        cookTime: "30 min",
        tags: ["Soup", "Sausage", "Pasta", "One-Pot", "Comfort Food", "Quick","New York Times"],
        description: "A hearty and comforting soup featuring sausage, tender tortellini, and vegetables in a flavorful broth, perfect for an easy weeknight meal.",
        image: "images/meals/meal-22.png",
        ingredients: [
          { name: "olive oil", quantity: 3, unit: "tbsp", section: "Pantry" },
          { name: "chicken sausage, sliced", quantity: "12–16", unit: "oz", section: "Meat" },
          { name: "fennel bulb, chopped", quantity: 1, unit: "", section: "Produce" },
          { name: "garlic, chopped", quantity: 4, unit: "cloves", section: "Produce" },
          { name: "salt", quantity: "", unit: "", section: "Pantry" },
          { name: "black pepper", quantity: "", unit: "", section: "Pantry" },
          { name: "chicken broth", quantity: 6, unit: "cups", section: "Pantry" },
          { name: "tortellini (cheese, spinach, or mushroom)", quantity: 10, unit: "oz", section: "Refrigerated" },
          { name: "mixed vegetables (snap peas, green beans, asparagus, kale, spinach, escarole, or peas)", quantity: 2, unit: "cups", section: "Produce" },
          { name: "grated Parmesan (for serving)", quantity: "", unit: "", section: "Dairy" }
        ],
        notes: "Jet fuel can't melt steel!"
      },
      {
        id: "turkey-chili",
        name: "NYT Turkey Chili",
        category: "Dinner / Chili",
        source: "New York Times",
        sourceUrl: "https://cooking.nytimes.com/recipes/1023225-turkey-chili",
        servings: 4,
        prepTime: "10 min",
        cookTime: "45 min",
        tags: ["Chili", "Turkey", "One-Pot", "Hearty", "Comfort Food", "Meal Prep","New York Times"],
        description: "A hearty and flavorful turkey chili made with tomatoes, chipotle peppers, and spices, perfect for a satisfying one-pot meal.",
        image: "images/meals/meal-23.png",
        ingredients: [
          { name: "olive oil", quantity: 3, unit: "tbsp", section: "Pantry" },
          { name: "White onion, diced", quantity: 1, unit: "", section: "Produce" },
          { name: "whole peeled tomatoes (canned)", quantity: 28, unit: "oz", section: "Pantry" },
          { name: "salt", quantity: "", unit: "", section: "Pantry" },
          { name: "chili powder", quantity: 2, unit: "tbsp", section: "Pantry" },
          { name: "ground turkey", quantity: 1, unit: "lb", section: "Meat" },
          { name: "chipotle peppers in adobo sauce", quantity: 7, unit: "oz", section: "Pantry" },
          { name: "shredded extra-sharp cheddar (optional)", quantity: "", unit: "", section: "Dairy" },
          { name: "sour cream (optional)", quantity: "", unit: "", section: "Dairy" },
          { name: "cilantro leaves (optional)", quantity: "", unit: "", section: "Produce" }
        ],
        notes: "Pizzagate doesn't sound so crazy anymore."
      },
      {
        id: "honey-chicken-rice-bowls",
        name: "WF Honey Chicken Rice Bowls",
        category: "Dinner / Bowl",
        source: "Frida Sofia Eats",
        sourceUrl: "https://www.fridasofiaeats.com/recipes/honey-salmon-rice-bowls",
        servings: 4,
        prepTime: "15 min",
        cookTime: "20 min",
        tags: ["Bowl", "Chicken", "Rice", "Healthy", "Quick", "Meal Prep", "Whole Foods"],
        description: "A flavorful rice bowl featuring honey-glazed chicken, jasmine rice, and fresh vegetables with a savory-sweet sauce.",
        image: "images/meals/meal-26.png",
        ingredients: [
          { name: "chicken breast or thighs, skin removed", quantity: "1.5–2", unit: "lb", section: "Meat" },
          { name: "ponzu sauce or soy sauce or sukiyaki sauce", quantity: 0.5, unit: "cup", section: "Pantry" },
          { name: "sesame oil", quantity: 0.33, unit: "cup", section: "Pantry" },
          { name: "honey", quantity: 3, unit: "tbsp", section: "Pantry" },
          { name: "jasmine rice", quantity: 1.5, unit: "cups", section: "Pantry" },
          { name: "cucumbers, thinly sliced", quantity: 4, unit: "", section: "Produce" },
          { name: "edamame, shelled", quantity: 1, unit: "cup", section: "Frozen" },
          { name: "ponzu sauce (for topping)", quantity: 2, unit: "tbsp", section: "Pantry" },
          { name: "sesame sauce (for topping)", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "honey (for topping)", quantity: 1, unit: "tbsp", section: "Pantry" }
        ],
        notes: "False flag!"
      },
      {
        id: "creamy-chicken-and-broccoli-pasta",
        name: "WF Creamy Chicken and Broccoli Pasta",
        category: "Dinner / Pasta",
        source: "Frida Sofia Eats",
        sourceUrl: "https://www.fridasofiaeats.com/recipes/creamy-chicken-and-broccoli-pasta",
        servings: 4,
        prepTime: "15 min",
        cookTime: "25 min",
        tags: ["Pasta", "Chicken", "Creamy", "Broccoli", "Comfort Food", "Quick", "Whole Foods"],
        description: "A creamy and comforting pasta dish with ground chicken, broccoli, and a rich Parmesan sauce, perfect for an easy weeknight dinner.",
        image: "images/meals/meal-27.png",
        ingredients: [
          { name: "protein pasta (radiatore)", quantity: 1, unit: "lb", section: "Pantry" },
          { name: "white or Yellow onion, diced", quantity: 1, unit: "", section: "Produce" },
          { name: "olive oil", quantity: "", unit: "", section: "Pantry" },
          { name: "ground chicken", quantity: 1, unit: "lb", section: "Meat" },
          { name: "Italian seasoning", quantity: 2, unit: "tsp", section: "Pantry" },
          { name: "salt", quantity: "1–2", unit: "tsp", section: "Pantry" },
          { name: "black pepper", quantity: 0.5, unit: "tsp", section: "Pantry" },
          { name: "broccoli", quantity: 8, unit: "oz", section: "Produce" },
          { name: "heavy cream", quantity: "1–1.5", unit: "cups", section: "Dairy" },
          { name: "Parmesan cheese, grated", quantity: "1–1.5", unit: "cups", section: "Dairy" },
          { name: "reserved pasta water", quantity: 0.5, unit: "cup", section: "Other" }
        ],
        notes: ""
      },
      {
        id: "beef-noodles",
        name: "WF Beef Noodles",
        category: "Dinner / Noodles",
        source: "Frida Sofia Eats",
        sourceUrl: "https://www.fridasofiaeats.com/recipes/beef-noodles",
        servings: 4,
        prepTime: "15 min",
        cookTime: "20 min",
        tags: ["Noodles", "Beef", "Quick", "One-Pan", "Weeknight", "Savory", "Whole Foods"],
        description: "A quick and savory noodle dish with ground beef, ramen noodles, and a flavorful ponzu-based sauce, perfect for an easy weeknight meal.",
        image: "images/meals/meal-28.png",
        ingredients: [
          { name: "ramen noodles", quantity: 8, unit: "oz", section: "Pantry" },
          { name: "ground beef", quantity: 1, unit: "lb", section: "Meat" },
          { name: "zucchini", quantity: 1, unit: "", section: "Produce" },
          { name: "ponzu sauce", quantity: 0.5, unit: "cup", section: "Pantry" },
          { name: "sesame oil", quantity: 0.33, unit: "cup", section: "Pantry" },
          { name: "olive oil", quantity: "", unit: "", section: "Pantry" }
        ],
        notes: ""
      },
      {
        id: "parmesan-rice-and-chicken-sausage",
        name: "WF Parmesan Rice and Chicken Sausage",
        category: "Dinner / Skillet",
        source: "Frida Sofia Eats",
        sourceUrl: "https://www.fridasofiaeats.com/recipes/parmesan-rice-and-chicken-sausage",
        servings: 4,
        prepTime: "10 min",
        cookTime: "25 min",
        tags: ["Rice", "Chicken Sausage", "One-Pan", "Comfort Food", "Quick", "Family-Friendly", "Whole Foods"],
        description: "A simple and comforting skillet meal with chicken sausage, basmati rice, spinach, and Parmesan cheese, finished with a touch of lemon.",
        image: "images/meals/meal-29.png",
        ingredients: [
          { name: "basmati rice", quantity: 1.5, unit: "cups", section: "Pantry" },
          { name: "Parmesan cheese, grated", quantity: 0.75, unit: "cup", section: "Dairy" },
          { name: "lemon", quantity: 1, unit: "", section: "Produce" },
          { name: "chicken sausage links", quantity: 4, unit: "", section: "Meat" },
          { name: "spinach", quantity: 2, unit: "cups", section: "Produce" },
          { name: "olive oil", quantity: "", unit: "", section: "Pantry" }
        ],
        notes: ""
      },
      {
        id: "boursin-chicken-sheet-pan",
        name: "WF Boursin Chicken Sheet Pan",
        category: "Dinner / Sheet Pan",
        source: "Frida Sofia Eats",
        sourceUrl: "https://www.fridasofiaeats.com/recipes/boursin-chicken-sheet-pan",
        servings: 4,
        prepTime: "10 min",
        cookTime: "30 min",
        tags: ["Sheet Pan", "Chicken", "Easy", "One-Pan", "Comfort Food", "Whole Foods"],
        description: "A simple and flavorful sheet pan meal with chicken thighs, vegetables, and creamy Boursin cheese, perfect for an easy weeknight dinner.",
        image: "images/meals/meal-30.png",
        ingredients: [
          { name: "yellow baby potatoes", quantity: 24, unit: "oz", section: "Produce" },
          { name: "boneless skinless chicken thighs", quantity: "1–1.5", unit: "lb", section: "Meat" },
          { name: "zucchini", quantity: 1, unit: "", section: "Produce" },
          { name: "red bell peppers", quantity: 2, unit: "", section: "Produce" },
          { name: "Boursin cheese", quantity: 1, unit: "package", section: "Dairy" },
          { name: "olive oil", quantity: "", unit: "", section: "Pantry" },
          { name: "salt", quantity: "", unit: "", section: "Pantry" },
          { name: "lemon juice (optional)", quantity: "1–2", unit: "tbsp", section: "Produce" }
        ],
        notes: ""
      },
      {
        id: "chicken-stroganoff",
        name: "TJ Chicken Stroganoff",
        category: "Dinner / Skillet",
        source: "Frida Sofia Eats",
        sourceUrl: "https://www.fridasofiaeats.com/recipes/chicken-stroganoff",
        servings: 4,
        prepTime: "15 min",
        cookTime: "25 min",
        tags: ["Skillet", "Chicken", "Creamy", "Comfort Food", "One-Pan", "Quick", "Trader Joe's"],
        description: "A creamy and comforting skillet dish with chicken sausage, mushrooms, and a rich, savory sauce, served over rice.",
        image: "images/meals/meal-31.png",
        ingredients: [
          { name: "olive oil", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "Yellow onion, diced", quantity: 1, unit: "", section: "Produce" },
          { name: "white mushrooms, sliced", quantity: 8, unit: "oz", section: "Produce" },
          { name: "pre-cooked cheddar chicken sausage, sliced", quantity: 12, unit: "oz", section: "Meat" },
          { name: "tomato paste", quantity: 3, unit: "tbsp", section: "Pantry" },
          { name: "Dijon mustard", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "soy sauce or coconut aminos", quantity: 3, unit: "tbsp", section: "Pantry" },
          { name: "chicken broth", quantity: 1, unit: "cup", section: "Pantry" },
          { name: "heavy cream", quantity: 1, unit: "cup", section: "Dairy" },
          { name: "basmati rice, cooked (for serving)", quantity: "", unit: "", section: "Pantry" }
        ],
        notes: ""
      },
      {
        id: "one-pan-greek-lemon-chicken-and-potatoes",
        name: "TJ One-Pan Greek Lemon Chicken and Potatoes",
        category: "Dinner / Sheet Pan",
        source: "Frida Sofia Eats",
        sourceUrl: "https://www.fridasofiaeats.com/recipes/one-pan-greek-lemon-chicken-and-potatoes",
        servings: 4,
        prepTime: "10 min",
        cookTime: "45 min",
        tags: ["Sheet Pan", "Chicken", "Potatoes", "One-Pan", "Easy", "Mediterranean", "Trader Joe's"],
        description: "A simple and flavorful one-pan meal with lemony chicken, roasted potatoes, and green beans, served with a cool tzatziki sauce.",
        image: "images/meals/meal-32.png",
        ingredients: [
          { name: "small potatoes", quantity: 24, unit: "oz", section: "Produce" },
          { name: "boneless skinless chicken thighs", quantity: 2, unit: "lb", section: "Meat" },
          { name: "green beans, trimmed", quantity: 10, unit: "oz", section: "Produce" },
          { name: "lemons", quantity: 2, unit: "", section: "Produce" },
          { name: "tzatziki dip", quantity: 6, unit: "oz", section: "Refrigerated" },
          { name: "olive oil", quantity: "", unit: "", section: "Pantry" },
          { name: "salt", quantity: "", unit: "", section: "Pantry" }
        ],
        notes: ""
      },
      {
        id: "easy-meat-loaf",
        name: "Slow Cooker Easy Meat Loaf",
        category: "Dinner / Slow Cooker",
        source: "Slow Cooker Tin Box",
        sourceUrl: "https://drive.google.com/file/d/1eym1auLLrpqe1aN8DjMvt5_ZNRvhYU0m/view?usp=drive_link",
        servings: 6,
        prepTime: "20 min",
        cookTime: "5–6 hours",
        tags: ["Slow Cooker", "Beef", "Comfort Food", "Family-Friendly"],
        description: "A simple and comforting slow cooker meat loaf made with ground beef, breadcrumbs, and a sweet and tangy ketchup glaze.",
        image: "images/meals/meal-33.png",
        ingredients: [
          { name: "ground beef", quantity: 1.5, unit: "lb", section: "Meat" },
          { name: "milk", quantity: 0.75, unit: "cup", section: "Dairy" },
          { name: "plain dry bread crumbs", quantity: 0.66, unit: "cup", section: "Pantry" },
          { name: "eggs, beaten", quantity: 2, unit: "", section: "Dairy" },
          { name: "Yellow onion, minced", quantity: 2, unit: "tbsp", section: "Produce" },
          { name: "salt", quantity: 1, unit: "tsp", section: "Pantry" },
          { name: "ground sage", quantity: 0.5, unit: "tsp", section: "Pantry" },
          { name: "ketchup", quantity: 0.5, unit: "cup", section: "Pantry" },
          { name: "brown sugar", quantity: 2, unit: "tbsp", section: "Pantry" },
          { name: "dry mustard", quantity: 1, unit: "tsp", section: "Pantry" }
        ],
        notes: ""
      },
      {
        id: "simple-salsa-steak",
        name: "5 Ingredient Simple Salsa Steak",
        category: "Dinner / Skillet",
        source: "5 Ingredient Tin Box",
        sourceUrl: "https://drive.google.com/file/d/1QJihINZ49iP3bkEa8BbIrGEwwlB8fg-R/view?usp=drive_link",
        servings: 4,
        prepTime: "2 hours",
        cookTime: "10 min",
        tags: ["Steak", "Quick", "Simple", "High-Protein"],
        description: "A simple and flavorful steak dish marinated in spicy salsa, lime juice, and cumin, then quickly cooked for an easy, protein-rich meal.",
        image: "images/meals/meal-34.png",
        ingredients: [
          { name: "spicy salsa", quantity: 1.5, unit: "cups", section: "Pantry" },
          { name: "lime juice", quantity: 3, unit: "tbsp", section: "Produce" },
          { name: "olive oil", quantity: 1.5, unit: "tbsp", section: "Pantry" },
          { name: "ground cumin", quantity: 0.75, unit: "tsp", section: "Pantry" },
          { name: "flank steak", quantity: 1.5, unit: "lb", section: "Meat" },
          { name: "Green onions, finely chopped", quantity: 1, unit: "", section: "Produce" }
        ],
        notes: ""
      },
      {
        id: "5-ingredient-asian-chicken-and-noodle-stir-fry",
        name: "5 Ingredient Asian Chicken and Noodle Stir-Fry",
        category: "Dinner / Noodles",
        source: "5 Ingredient Tin Box",
        sourceUrl: "https://drive.google.com/file/d/1KBzIENNFFa2AgxyZIzOQOURzttN0I7zg/view?usp=drive_link",
        servings: 4,
        prepTime: "15 min",
        cookTime: "20 min",
        tags: ["Noodles", "Chicken", "Stir-Fry", "Quick", "One-Pan"],
        description: "A quick and simple stir-fry with chicken, rice noodles, and vegetables in a sweet and savory stir-fry sauce.",
        image: "images/meals/meal-35.png",
        ingredients: [
          { name: "Pad Thai rice noodles (thin)", quantity: 8, unit: "oz", section: "Pantry" },
          { name: "vegetable oil", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "boneless skinless chicken breasts, cut into pieces", quantity: 1, unit: "lb", section: "Meat" },
          { name: "stir-fry sauce", quantity: 12, unit: "oz", section: "Pantry" },
          { name: "water", quantity: 0.25, unit: "cup", section: "Pantry" },
          { name: "brown sugar", quantity: 2, unit: "tbsp", section: "Pantry" },
          { name: "frozen stir-fry vegetable blend", quantity: 16, unit: "oz", section: "Frozen" }
        ],
        notes: ""
      },
      {
        id: "5-ingredient-pork-and-asparagus-stir-fry",
        name: "5 Ingredient Pork and Asparagus Stir-Fry",
        category: "Dinner / Stir-Fry",
        source: "5 Ingredient Tin Box",
        sourceUrl: "https://drive.google.com/file/d/1_jhPjtJYR-NHfzVSOM8XDtZW6gNjZ3pu/view?usp=drive_link",
        servings: 4,
        prepTime: "15 min",
        cookTime: "15 min",
        tags: ["Stir-Fry", "Pork", "Quick", "One-Pan"],
        description: "A quick and simple stir-fry with pork tenderloin, asparagus, and a savory black bean sauce, perfect for an easy weeknight meal.",
        image: "images/meals/meal-36.png",
        ingredients: [
          { name: "vegetable oil", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "pork tenderloin, cut into pieces", quantity: 12, unit: "oz", section: "Meat" },
          { name: "Chinese black bean sauce", quantity: 3, unit: "tbsp", section: "Pantry" },
          { name: "black pepper", quantity: 0.5, unit: "tsp", section: "Pantry" },
          { name: "asparagus, cut into pieces", quantity: 12, unit: "oz", section: "Produce" },
          { name: "water", quantity: "2–3", unit: "tbsp", section: "Pantry" },
          { name: "cooked rice (optional)", quantity: "", unit: "", section: "Pantry" }
        ],
        notes: ""
      }
    ];
