const recipes = [
      {
        id: "lemon-butter-chicken-sheet-pan",
        name: "Trader Joe's Lemon Butter Chicken Sheet Pan",
        category: "Dinner / Sheet Pan",
        source: "Custom",
        sourceUrl: "",
        servings: 4,
        prepTime: "10 min",
        cookTime: "40 min",
        tags: ["Trader Joe's", "Sheet Pan", "Chicken", "Easy"],
        description: "A simple sheet pan dinner with chicken breast, baby potatoes, green beans, lemon butter, garlic, and seasoning.",
        ingredients: [
          { name: "Chicken breast", quantity: 1.5, unit: "lb", section: "Meat" },
          { name: "Baby potatoes", quantity: 1, unit: "lb", section: "Produce" },
          { name: "Green beans", quantity: 12, unit: "oz", section: "Produce" },
          { name: "Butter", quantity: 4, unit: "tbsp", section: "Dairy" },
          { name: "Garlic", quantity: 4, unit: "", section: "Produce" },
          { name: "Lemons", quantity: 1, unit: "", section: "Produce" },
          { name: "Olive oil", quantity: 2, unit: "tbsp", section: "Pantry" },
          { name: "Italian seasoning", quantity: 1, unit: "tsp", section: "Pantry" },
          { name: "Paprika", quantity: 1, unit: "tsp", section: "Pantry" },
          { name: "Salt", quantity: "to taste", unit: "", section: "Pantry" },
          { name: "Black pepper", quantity: "to taste", unit: "", section: "Pantry" }
        ],
        notes: "Good option for a low-effort dinner night."
      },
      {
        id: "sweet-potato-cheeseburger-skillet",
        name: "Trader Joe's Sweet Potato Cheeseburger Skillet",
        category: "Dinner",
        source: "Custom",
        sourceUrl: "",
        servings: 4,
        prepTime: "10 min",
        cookTime: "20 min",
        tags: ["Beef", "Skillet", "Sweet Potato", "Quick"],
        description: "A simple beef and sweet potato skillet with onion, garlic, ketchup, mustard, and cheddar cheese.",
        ingredients: [
          { name: "Ground beef", quantity: 1, unit: "lb", section: "Meat" },
          { name: "Sweet potatoes", quantity: 2, unit: "", section: "Produce" },
          { name: "Yellow onion", quantity: 1, unit: "", section: "Produce" },
          { name: "Garlic", quantity: 3, unit: "", section: "Produce" },
          { name: "Olive oil", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "Ketchup", quantity: 0.25, unit: "cup", section: "Pantry" },
          { name: "Mustard", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "Cheddar cheese", quantity: 1.5, unit: "cups", section: "Dairy" },
          { name: "Salt", quantity: "to taste", unit: "", section: "Pantry" },
          { name: "Black pepper", quantity: "to taste", unit: "", section: "Pantry" }
        ],
        notes: "Taco seasoning works well here if you want a different flavor."
      },
      {
        id: "french-onion-chicken-orzo",
        name: "Trader Joe's French Onion Chicken Orzo",
        category: "Dinner",
        source: "Custom",
        sourceUrl: "",
        servings: 4,
        prepTime: "10 min",
        cookTime: "35 min",
        tags: ["Chicken", "Orzo", "Comfort Food", "One Pan"],
        description: "A cozy chicken and orzo dinner with caramelized onions, beef broth, gruyere, Parmesan, and thyme.",
        ingredients: [
          { name: "Chicken breast", quantity: 1, unit: "lb", section: "Meat" },
          { name: "Yellow onion", quantity: 2, unit: "", section: "Produce" },
          { name: "Garlic", quantity: 3, unit: "", section: "Produce" },
          { name: "Butter", quantity: 3, unit: "tbsp", section: "Dairy" },
          { name: "Olive oil", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "Orzo pasta", quantity: 1, unit: "cup", section: "Pantry" },
          { name: "Beef broth", quantity: 2.5, unit: "cups", section: "Pantry" },
          { name: "Gruyere cheese", quantity: 1, unit: "cup", section: "Dairy" },
          { name: "Parmesan cheese", quantity: 0.5, unit: "cup", section: "Dairy" },
          { name: "Fresh thyme", quantity: 2, unit: "tsp", section: "Produce" },
          { name: "Salt", quantity: "to taste", unit: "", section: "Pantry" },
          { name: "Black pepper", quantity: "to taste", unit: "", section: "Pantry" }
        ],
        notes: "Keep extra broth nearby if the orzo absorbs too much liquid."
      },
      {
        id: "spinach-artichoke-orzo",
        name: "Trader Joe's Spinach and Artichoke Orzo",
        category: "Dinner / Vegetarian",
        source: "Custom",
        sourceUrl: "",
        servings: 4,
        prepTime: "10 min",
        cookTime: "20 min",
        tags: ["Vegetarian", "Orzo", "Creamy", "Trader Joe's"],
        description: "A creamy vegetarian orzo dish with spinach, artichokes, cream cheese, Parmesan, and lemon juice.",
        ingredients: [
          { name: "Orzo pasta", quantity: 1, unit: "cup", section: "Pantry" },
          { name: "Garlic", quantity: 3, unit: "", section: "Produce" },
          { name: "Butter", quantity: 2, unit: "tbsp", section: "Dairy" },
          { name: "Olive oil", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "Vegetable broth", quantity: 2.5, unit: "cups", section: "Pantry" },
          { name: "Spinach", quantity: 5, unit: "oz", section: "Produce" },
          { name: "Artichoke hearts", quantity: 1, unit: "can", section: "Pantry" },
          { name: "Cream cheese", quantity: 4, unit: "oz", section: "Dairy" },
          { name: "Parmesan cheese", quantity: 0.5, unit: "cup", section: "Dairy" },
          { name: "Lemon juice", quantity: 1, unit: "tbsp", section: "Produce" },
          { name: "Salt", quantity: "to taste", unit: "", section: "Pantry" },
          { name: "Black pepper", quantity: "to taste", unit: "", section: "Pantry" }
        ],
        notes: "Can be served as a vegetarian main or as a side with chicken."
      },
      {
        id: "chicken-noodle-bowl",
        name: "Trader Joe's Chicken Noodle Bowl",
        category: "Dinner",
        source: "Custom",
        sourceUrl: "",
        servings: 4,
        prepTime: "10 min",
        cookTime: "15 min",
        tags: ["Chicken", "Noodles", "Quick", "Trader Joe's"],
        description: "A quick chicken noodle bowl with stir fry noodles, carrots, cucumbers, garlic, soy sauce, and sesame oil.",
        ingredients: [
          { name: "Chicken breast", quantity: 1, unit: "lb", section: "Meat" },
          { name: "Stir fry noodles", quantity: 12, unit: "oz", section: "Pantry" },
          { name: "Carrots", quantity: 2, unit: "", section: "Produce" },
          { name: "Cucumbers", quantity: 1, unit: "", section: "Produce" },
          { name: "Garlic", quantity: 2, unit: "", section: "Produce" },
          { name: "Soy sauce", quantity: 0.25, unit: "cup", section: "Pantry" },
          { name: "Sesame oil", quantity: 1, unit: "tsp", section: "Pantry" },
          { name: "Olive oil", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "Salt", quantity: "to taste", unit: "", section: "Pantry" },
          { name: "Black pepper", quantity: "to taste", unit: "", section: "Pantry" }
        ],
        notes: "This is adapted from the shrimp version by replacing shrimp with chicken."
      },
      {
        id: "salsa-verde-chicken-couscous",
        name: "Trader Joe's Salsa Verde Chicken and Couscous",
        category: "Dinner",
        source: "Custom",
        sourceUrl: "",
        servings: 4,
        prepTime: "10 min",
        cookTime: "20 min",
        tags: ["Chicken", "Couscous", "Quick", "Trader Joe's"],
        description: "A quick chicken dinner with couscous, chicken broth, salsa verde, garlic, and olive oil.",
        ingredients: [
          { name: "Chicken breast", quantity: 1, unit: "lb", section: "Meat" },
          { name: "Couscous", quantity: 1, unit: "cup", section: "Pantry" },
          { name: "Chicken broth", quantity: 1.5, unit: "cups", section: "Pantry" },
          { name: "Salsa verde", quantity: 0.5, unit: "cup", section: "Pantry" },
          { name: "Garlic", quantity: 2, unit: "", section: "Produce" },
          { name: "Olive oil", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "Salt", quantity: "to taste", unit: "", section: "Pantry" },
          { name: "Black pepper", quantity: "to taste", unit: "", section: "Pantry" }
        ],
        notes: "Good for leftovers and easy to customize."
      },
      {
        id: "soyaki-beef-bowl",
        name: "Trader Joe's Soyaki Beef Bowl (Original)",
        category: "Dinner",
        source: "Custom",
        sourceUrl: "",
        servings: 4,
        prepTime: "10 min",
        cookTime: "15 min",
        tags: ["Beef", "Rice Bowl", "Quick", "Trader Joe's"],
        description: "A fast rice bowl with ground beef, white rice, Soyaki sauce, garlic, and green onions.",
        ingredients: [
          { name: "Ground beef", quantity: 1, unit: "lb", section: "Meat" },
          { name: "White rice", quantity: 2, unit: "cups", section: "Pantry" },
          { name: "Water", quantity: 2, unit: "cups", section: "Pantry" },
          { name: "Soyaki sauce", quantity: 0.5, unit: "cup", section: "Pantry" },
          { name: "Garlic", quantity: 3, unit: "", section: "Produce" },
          { name: "Green onions", quantity: 2, unit: "", section: "Produce" },
          { name: "Olive oil", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "Salt", quantity: "to taste", unit: "", section: "Pantry" },
          { name: "Black pepper", quantity: "to taste", unit: "", section: "Pantry" }
        ],
        notes: "One of the fastest weeknight options."
      },
      {
        id: "slow-cooker-steak-and-potatoes",
        name: "Trader Joe's Slow Cooker Steak and Potatoes",
        category: "Dinner / Slow Cooker",
        source: "Custom",
        sourceUrl: "",
        servings: 4,
        prepTime: "10 min",
        cookTime: "6 hrs",
        tags: ["Beef", "Slow Cooker", "Potatoes", "Comfort Food"],
        description: "A slow cooker steak and potato dinner with garlic, beef broth, olive oil, and Italian seasoning.",
        ingredients: [
          { name: "Shaved steak", quantity: 1.5, unit: "lb", section: "Meat" },
          { name: "Baby potatoes", quantity: 1.5, unit: "lb", section: "Produce" },
          { name: "Garlic", quantity: 4, unit: "", section: "Produce" },
          { name: "Beef broth", quantity: 2, unit: "cups", section: "Pantry" },
          { name: "Olive oil", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "Italian seasoning", quantity: 1, unit: "tsp", section: "Pantry" },
          { name: "Salt", quantity: "to taste", unit: "", section: "Pantry" },
          { name: "Black pepper", quantity: "to taste", unit: "", section: "Pantry" }
        ],
        notes: "Good make-ahead dinner."
      },
      {
        id: "chicken-sausage-pasta-bake",
        name: "Trader Joe's Chicken Sausage Pasta Bake",
        category: "Dinner",
        source: "Custom",
        sourceUrl: "",
        servings: 4,
        prepTime: "10 min",
        cookTime: "25 min",
        tags: ["Chicken Sausage", "Pasta", "Bake", "Easy"],
        description: "A pasta bake with chicken sausage, pasta, crushed tomatoes, garlic, mozzarella, Parmesan, and Italian seasoning.",
        ingredients: [
          { name: "Chicken sausage", quantity: 12, unit: "oz", section: "Meat" },
          { name: "Pasta", quantity: 12, unit: "oz", section: "Pantry" },
          { name: "Crushed tomatoes", quantity: 1, unit: "can", section: "Pantry" },
          { name: "Garlic", quantity: 3, unit: "", section: "Produce" },
          { name: "Olive oil", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "Mozzarella cheese", quantity: 1.5, unit: "cups", section: "Dairy" },
          { name: "Parmesan cheese", quantity: 0.5, unit: "cup", section: "Dairy" },
          { name: "Italian seasoning", quantity: 1, unit: "tsp", section: "Pantry" },
          { name: "Salt", quantity: "to taste", unit: "", section: "Pantry" },
          { name: "Black pepper", quantity: "to taste", unit: "", section: "Pantry" }
        ],
        notes: "Good easy pasta-bake option."
      },
      {
        id: "cheesy-chicken-sausage-rice-orzo",
        name: "Trader Joe's Cheesy Chicken Sausage Rice and Orzo",
        category: "Dinner",
        source: "Custom",
        sourceUrl: "",
        servings: 4,
        prepTime: "10 min",
        cookTime: "30 min",
        tags: ["Chicken Sausage", "Rice", "Orzo", "Bake"],
        description: "A cheesy baked rice and orzo dinner with chicken sausage, chicken broth, garlic, butter, and cheddar cheese.",
        ingredients: [
          { name: "Chicken sausage", quantity: 12, unit: "oz", section: "Meat" },
          { name: "White rice", quantity: 1, unit: "cup", section: "Pantry" },
          { name: "Orzo pasta", quantity: 0.5, unit: "cup", section: "Pantry" },
          { name: "Chicken broth", quantity: 2.5, unit: "cups", section: "Pantry" },
          { name: "Garlic", quantity: 3, unit: "", section: "Produce" },
          { name: "Butter", quantity: 2, unit: "tbsp", section: "Dairy" },
          { name: "Olive oil", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "Cheddar cheese", quantity: 1.5, unit: "cups", section: "Dairy" },
          { name: "Salt", quantity: "to taste", unit: "", section: "Pantry" },
          { name: "Black pepper", quantity: "to taste", unit: "", section: "Pantry" }
        ],
        notes: "If picky eaters object to extras, keep this one simple."
      },
      {
        id: "spicy-quick-chicken-chili",
        name: "Trader Joe's Spicy Quick Chicken Chili",
        category: "Dinner",
        source: "Custom",
        sourceUrl: "",
        servings: 4,
        prepTime: "10 min",
        cookTime: "25 min",
        tags: ["Chicken", "Chili", "Quick", "Spicy"],
        description: "A fast, hearty chicken chili with beans, corn, and a creamy finish from cream cheese.",
        ingredients: [
          { name: "Chicken breast", quantity: 2, unit: "cups", section: "Meat" },
          { name: "Olive oil", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "Yellow onion", quantity: 1, unit: "", section: "Produce" },
          { name: "Garlic", quantity: 3, unit: "", section: "Produce" },
          { name: "Chili powder", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "Ground cumin", quantity: 1, unit: "tsp", section: "Pantry" },
          { name: "Paprika", quantity: 1, unit: "tsp", section: "Pantry" },
          { name: "Crushed red pepper flakes", quantity: 0.5, unit: "tsp", section: "Pantry" },
          { name: "Diced tomatoes", quantity: 1, unit: "can", section: "Pantry" },
          { name: "Black beans", quantity: 1, unit: "can", section: "Pantry" },
          { name: "Corn", quantity: 1, unit: "cup", section: "Frozen" },
          { name: "Chicken broth", quantity: 2, unit: "cups", section: "Pantry" },
          { name: "Cream cheese", quantity: 4, unit: "oz", section: "Dairy" },
          { name: "Lime juice", quantity: 1, unit: "tbsp", section: "Produce" },
          { name: "Salt", quantity: "to taste", unit: "", section: "Pantry" },
          { name: "Black pepper", quantity: "to taste", unit: "", section: "Pantry" }
        ],
        notes: "Great for leftovers. Adjust spice level by increasing or reducing red pepper flakes."
      },
      {
        id: "soyaki-shaved-steak-bowl",
        name: "Trader Joe's Soyaki Shaved Steak Bowl",
        category: "Dinner",
        source: "Custom",
        sourceUrl: "",
        servings: 4,
        prepTime: "10 min",
        cookTime: "20 min",
        tags: ["Beef", "Rice Bowl", "Quick", "Trader Joe's"],
        description: "A quick rice bowl with shaved steak, peppers, onions, garlic, and Trader Joe's Soyaki sauce.",
        ingredients: [
          { name: "Shaved steak", quantity: 1, unit: "lb", section: "Meat" },
          { name: "Soyaki sauce", quantity: 0.5, unit: "cup", section: "Pantry" },
          { name: "Bell peppers", quantity: 2, unit: "", section: "Produce" },
          { name: "Yellow onion", quantity: 1, unit: "", section: "Produce" },
          { name: "Garlic", quantity: 3, unit: "", section: "Produce" },
          { name: "Olive oil", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "White rice", quantity: 2, unit: "cups", section: "Pantry" },
          { name: "Water", quantity: 2, unit: "cups", section: "Pantry" },
          { name: "Salt", quantity: "to taste", unit: "", section: "Pantry" },
          { name: "Black pepper", quantity: "to taste", unit: "", section: "Pantry" }
        ],
        notes: "Slice vegetables thin so they cook quickly. Great weeknight option."
      },
      {
        id: "beef-stir-fry-noodles",
        name: "Trader Joe's Beef Stir Fry Noodles",
        category: "Dinner",
        source: "Custom",
        sourceUrl: "",
        servings: 4,
        prepTime: "10 min",
        cookTime: "15 min",
        tags: ["Beef", "Noodles", "Stir Fry", "Quick"],
        description: "A fast stir fry with shaved steak, pre-cooked noodles, vegetables, and Soyaki sauce.",
        ingredients: [
          { name: "Shaved steak", quantity: 1, unit: "lb", section: "Meat" },
          { name: "Stir fry noodles", quantity: 1, unit: "package", section: "Refrigerated" },
          { name: "Soyaki sauce", quantity: 0.5, unit: "cup", section: "Pantry" },
          { name: "Frozen stir fry vegetables", quantity: 1, unit: "bag", section: "Frozen" },
          { name: "Olive oil", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "Garlic", quantity: 2, unit: "", section: "Produce" },
          { name: "Salt", quantity: "to taste", unit: "", section: "Pantry" },
          { name: "Black pepper", quantity: "to taste", unit: "", section: "Pantry" }
        ],
        notes: "Very quick meal—great for busy nights."
      },
      {
        id: "sesame-chicken-veggie-rice-bowl",
        name: "Trader Joe's Sesame Chicken Veggie Rice Bowl",
        category: "Dinner",
        source: "Custom",
        sourceUrl: "",
        servings: 4,
        prepTime: "10 min",
        cookTime: "20 min",
        tags: ["Chicken", "Rice Bowl", "Stir Fry", "Quick"],
        description: "A simple rice bowl with chicken, vegetables, and sesame sauce.",
        ingredients: [
          { name: "Chicken breast", quantity: 1, unit: "lb", section: "Meat" },
          { name: "White rice", quantity: 2, unit: "cups", section: "Pantry" },
          { name: "Water", quantity: 2, unit: "cups", section: "Pantry" },
          { name: "Frozen stir fry vegetables", quantity: 1, unit: "bag", section: "Frozen" },
          { name: "Sesame sauce", quantity: 0.5, unit: "cup", section: "Pantry" },
          { name: "Garlic", quantity: 2, unit: "", section: "Produce" },
          { name: "Olive oil", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "Sesame oil", quantity: 1, unit: "tsp", section: "Pantry" },
          { name: "Salt", quantity: "to taste", unit: "", section: "Pantry" },
          { name: "Black pepper", quantity: "to taste", unit: "", section: "Pantry" }
        ],
        notes: "Add extra sesame oil for more flavor."
      },
      {
        id: "chicken-wonton-stir-fry",
        name: "Trader Joe's Chicken Wonton Stir Fry",
        category: "Dinner",
        source: "Custom",
        sourceUrl: "",
        servings: 4,
        prepTime: "10 min",
        cookTime: "15 min",
        tags: ["Trader Joe's", "Wontons", "Stir Fry", "Quick"],
        description: "A quick stir fry with chicken wontons, frozen vegetables, Soyaki sauce, garlic, sesame oil, and green onions.",
        ingredients: [
          { name: "Chicken wontons", quantity: 1, unit: "bag", section: "Frozen" },
          { name: "Frozen stir fry vegetables", quantity: 1, unit: "bag", section: "Frozen" },
          { name: "Soyaki sauce", quantity: 0.5, unit: "cups", section: "Pantry" },
          { name: "Garlic", quantity: 2, unit: "", section: "Produce" },
          { name: "Olive oil", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "Green onions", quantity: 2, unit: "", section: "Produce" },
          { name: "Sesame oil", quantity: 1, unit: "tsp", section: "Pantry" },
          { name: "Salt", quantity: "to taste", unit: "", section: "Pantry" },
          { name: "Black pepper", quantity: "to taste", unit: "", section: "Pantry" }
        ],
        notes: "Good fast freezer meal. Keep the wontons whole and avoid over-stirring once they are heated."
      },
      {
        id: "pesto-chicken-sandwich",
        name: "Trader Joe's Pesto Chicken Sandwich",
        category: "Dinner / Sandwiches",
        source: "Custom",
        sourceUrl: "",
        servings: 4,
        prepTime: "10 min",
        cookTime: "15 min",
        tags: ["Chicken", "Sandwich", "Pesto", "Quick"],
        description: "A pesto chicken sandwich with Havarti cheese, brioche buns, pesto, tomatoes, and butter.",
        ingredients: [
          { name: "Chicken breast", quantity: 1, unit: "lb", section: "Meat" },
          { name: "Havarti cheese", quantity: 4, unit: "slices", section: "Dairy" },
          { name: "Brioche buns", quantity: 4, unit: "buns", section: "Pantry" },
          { name: "Pesto", quantity: 4, unit: "oz", section: "Refrigerated" },
          { name: "Tomatoes", quantity: 1, unit: "", section: "Produce" },
          { name: "Butter", quantity: "to taste", unit: "", section: "Dairy" }
        ],
        notes: "Good quick sandwich dinner."
      },
      {
        id: "angela-josh-spicy-soy-garlic-turkey-bowl",
        name: "Angela and Josh's Spicy Soy Garlic Turkey Bowl",
        category: "Dinner",
        source: "Custom",
        sourceUrl: "",
        servings: 4,
        prepTime: "15 min",
        cookTime: "25 min",
        tags: ["Turkey", "Rice Bowl", "Spicy", "Quick"],
        description: "A spicy soy garlic turkey bowl with rice, bok choy, pickled radishes, and a creamy curry sauce.",
        ingredients: [
          { name: "White rice", quantity: 1, unit: "cup", section: "Pantry" },
          { name: "Water", quantity: 1.5, unit: "cups", section: "Pantry" },
          { name: "Salt", quantity: 0.5, unit: "tsp", section: "Pantry" },
          { name: "Apple cider vinegar", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "Sesame oil", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "Green onions", quantity: 2, unit: "", section: "Produce" },
          { name: "Black pepper", quantity: 1, unit: "tsp", section: "Pantry" },
          { name: "Radishes", quantity: 3, unit: "oz", section: "Produce" },
          { name: "Mayonnaise", quantity: 0.25, unit: "cup", section: "Dairy" },
          { name: "Red curry paste", quantity: 2, unit: "tbsp", section: "Pantry" },
          { name: "Honey", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "Soy sauce", quantity: 0.25, unit: "cup", section: "Pantry" },
          { name: "Brown sugar", quantity: 0.25, unit: "cup", section: "Pantry" },
          { name: "Garlic", quantity: 2, unit: "", section: "Produce" },
          { name: "Ginger", quantity: 1, unit: "tsp", section: "Produce" },
          { name: "Red pepper flakes", quantity: 0.25, unit: "tsp", section: "Pantry" },
          { name: "Coconut oil", quantity: 1, unit: "tbsp", section: "Pantry" },
          { name: "Ground turkey", quantity: 1.5, unit: "lb", section: "Meat" },
          { name: "Bok choy", quantity: 2, unit: "", section: "Produce" },
          { name: "Sesame seeds", quantity: 1, unit: "tbsp", section: "Pantry" }
        ],
        notes: "Great balance of spicy, savory, and fresh."
      },

      {
        id: "21",
        name: "Angela and Josh's Orecchiette with Chicken Sausage, Fennel, and Asparagus",
        category: "Dinner",
        source: "Custom",
        sourceUrl: "",
        servings: 4,
        prepTime: "10 min",
        cookTime: "25 min",
        tags: ["Chicken Sausage", "Pasta", "Asparagus", "Dinner"],
        description: "Orecchiette pasta with chicken sausage, fennel, asparagus, lemon, capers, and pecorino romano.",
        ingredients: [
          { name: "Olive oil", quantity: 3, unit: "tbsp", section: "Pantry" },
          { name: "Chicken sausage", quantity: 1, unit: "lb", section: "Meat" },
          { name: "Fennel", quantity: 1, unit: "", section: "Produce" },
          { name: "Garlic", quantity: 3, unit: "", section: "Produce" },
          { name: "Red pepper flakes", quantity: 0.25, unit: "tsp", section: "Pantry" },
          { name: "White wine", quantity: 1, unit: "cup", section: "Pantry" },
          { name: "Chicken broth", quantity: 2, unit: "cups", section: "Pantry" },
          { name: "Lemon juice", quantity: 0.5, unit: "cup", section: "Produce" },
          { name: "Capers", quantity: 2, unit: "tbsp", section: "Pantry" },
          { name: "Orecchiette pasta", quantity: 8, unit: "oz", section: "Pantry" },
          { name: "Asparagus", quantity: 0.5, unit: "lb", section: "Produce" },
          { name: "Pecorino romano cheese", quantity: 0.5, unit: "cup", section: "Dairy" },
          { name: "Salt", quantity: 1, unit: "tsp", section: "Pantry" },
          { name: "Black pepper", quantity: 0.5, unit: "tsp", section: "Pantry" }
        ],
        notes: "Bright, savory pasta dinner with chicken sausage and vegetables."
      }
    ];
